twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        upload_dir: '/uploads'
        css_dir: '/css'
        js_dir: '/js'


when@test:
    twig:
        strict_variables: true
